name: Publish binaries

on:
  push:
    tags:
      - "v**-edgedb"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 50

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.13'

    - name: Build
      run: |
        PREFIX=$(mktemp -d)
        DISTRIBUTION_DIR="${PREFIX}/src/github.com/distribution/distribution"
        mkdir -p "${DISTRIBUTION_DIR}"
        mkdir -p "${GITHUB_WORKSPACE}/bin"
        rsync -a "${GITHUB_WORKSPACE}/" "${DISTRIBUTION_DIR}/"
        cd "${DISTRIBUTION_DIR}"
        CGO_ENABLED=0 PREFIX="${PREFIX}" GOPATH="${PREFIX}" make bin/registry
        for asset in ./bin/*; do
          xz -c -9 "${asset}" > "${GITHUB_WORKSPACE}/bin/${asset}.xz"
        done

    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        assets=()
        for asset in ./bin/*.xz; do
          assets+=("-a" "${asset}")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
